import {StyleSheet} from 'react-native';
import {SIZES, COLORS} from '../../constants';
export default styles = StyleSheet.create({
  bodyContainer: {
    width: SIZES.width,
    height: SIZES.height,
    flexDirection: 'column',
    justifyContent: 'space-between',
    bottom: -10,
  },
  nameContainer: {
    width: SIZES.width,
    height: SIZES.height * 0.2,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: SIZES.height * 0.1,
  },
  title: {
    fontSize: SIZES.padding2,
    fontWeight: 'bold',
    color: 'white',
  },
  headingText: {
    fontSize: SIZES.padding,
    fontWeight: 'bold',
    color: 'white',
  },
  subHeading: {
    color: 'white',
    fontSize: SIZES.h2,
    fontWeight: 'bold',
  },
  paragrapgh: {
    fontSize: SIZES.h3,
    color: 'white',
    fontWeight: 'bold',
  },

  textInputStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
    width: '80%',
    height: 48,
    borderRadius: 20,
    paddingHorizontal: 16,
    shadowOffset: {width: 0, height: 1},
    shadowRadius: 2,
    elevation: 2,
    shadowOpacity: 0.4,
    marginTop: 10,
  },
  gradientContainer: {
    width: SIZES.width,
    height: SIZES.height * 0.75,
    borderTopLeftRadius: 60,
    borderTopRightRadius: 60,
    flexDirection: 'column',
    alignItems: 'center',
  },
  userIcon: {
    height: SIZES.width * 0.22,
    width: SIZES.width * 0.22,
    borderRadius: (SIZES.width * 0.22) / 2,
    borderColor: 'white',
    borderWidth: 2,
    justifyContent: 'center',
    alignItems: 'center',
    top: -((SIZES.width * 0.2) / 2),
  },
  userImage: {
    height: SIZES.width * 0.2,
    width: SIZES.width * 0.2,
    borderRadius: (SIZES.width * 0.2) / 2,
    overflow: 'hidden',
    backgroundColor: 'red',
  },
  viewContainer: {
    width: '90%',
    height: '10%',
    borderBottomWidth: 2,
    borderBottomColor: 'white',
    flexDirection: 'row',
  },
  socialContainer: {
    width: '100%',
    height: '28%',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  icon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    overflow: 'hidden',
  },
  iconView: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    width: '15%',
    height: '100%',
  },
  textView: {
    width: '70%',
    paddingHorizontal: '5%',
    flexDirection: 'column',
    justifyContent: 'space-around',
  },
});
