import React, {useState} from 'react';
import {Text, View, ScrollView} from 'react-native';
import BackgroundImageApp from '../../components/common/BackgroundImageApp';
import HeaderTest from '../../components/common/HeaderTest';
import ModalApp from '../../components/common/ModalApp';
import styles from './styles';
const TermsScreen = ({navigation}) => {
  const [backModal, setBackModal] = useState(false);
  const handleContinue = () => setBackModal(true);
  const BackScreen = navigation.goBack;

  return (
    <BackgroundImageApp>
      <HeaderTest headerText="Terms & Conditions" BackScreen={handleContinue} />
      <ModalApp
        visible={backModal}
        feedback="Do you want go back?"
        quit={BackScreen}
        continueTest={() => setBackModal(false)}
        quitText="Go Back"
        continueTestText="Continue"
      />
      <View style={styles.bodyContainer}>
        <View style={styles.scrollView}>
          <ScrollView>
            <Text style={[styles.paragrapgh, {color: 'black'}]}>
              Privacy Policy Last updated: December 05, 2021 This Privacy Policy
              describes Our policies and procedures on the collection, use and
              disclosure of Your information when You use the Service and tells
              You about Your privacy rights and how the law protects You. We use
              Your Personal data to provide and improve the Service. By using
              the Service, You agree to the collection and use of information in
              accordance with this Privacy Policy. This Privacy Policy has been
              created with the help of the Privacy Policy Generator.
              Interpretation and Definitions Interpretation The words of which
              the initial letter is capitalized have meanings defined under the
              following conditions. The following definitions shall have the
              same meaning regardless of whether they appear in singular or in
              plural. Definitions For the purposes of this Privacy Policy:
              Account means a unique account created for You to access our
              Service or parts of our Service. Affiliate means an entity that
              controls, is controlled by or is under common control with a
              party, where "control" means ownership of 50% or more of the
              shares, equity interest or other securities entitled to vote for
              election of directors or other managing authority. Application
              means the software program provided by the Company downloaded by
              You on any electronic device, named Dyslexia Aid Company (referred
              to as either "the Company", "We", "Us" or "Our" in this Agreement)
              refers to Dyslexia Aid. Country refers to: Pakistan Device means
              any device that can access the Service such as a computer, a
              cellphone or a digital tablet. Personal Data is any information
              that relates to an identified or identifiable individual. Service
              refers to the Application. Service Provider means any natural or
              legal person who processes the data on behalf of the Company. It
              refers to third-party companies or individuals employed by the
              Company to facilitate the Service, to provide the Service on
              behalf of the Company, to perform services related to the Service
              or to assist the Company in analyzing how the Service is used.
              Usage Data refers to data collected automatically, either
              generated by the use of the Service or from the Service
              infrastructure itself (for example, the duration of a page visit).
              You means the individual accessing or using the Service, or the
              company, or other legal entity on behalf of which such individual
              is accessing or using the Service, as applicable. Collecting and
              Using Your Personal Data Types of Data Collected Personal Data
              While using Our Service, We may ask You to provide Us with certain
              personally identifiable information that can be used to contact or
              identify You. Personally identifiable information may include, but
              is not limited to: Email address First name and last name Usage
              Data Usage Data Usage Data is collected automatically when using
              the Service. Usage Data may include information such as Your
              Device's Internet Protocol address (e.g. IP address), browser
              type, browser version, the pages of our Service that You visit,
              the time and date of Your visit, the time spent on those pages,
              unique device identifiers and other diagnostic data. When You
              access the Service by or through a mobile device, We may collect
              certain information automatically, including, but not limited to,
              the type of mobile device You use, Your mobile device unique ID,
              the IP address of Your mobile device, Your mobile operating
              system, the type of mobile Internet browser You use, unique device
              identifiers and other diagnostic data. We may also collect
              information that Your browser sends whenever You visit our Service
              or when You access the Service by or through a mobile device.
            </Text>
          </ScrollView>
        </View>
      </View>
    </BackgroundImageApp>
  );
};

export default TermsScreen;
