import {StyleSheet} from 'react-native';
import {SIZES, COLORS} from '../../../../constants';
export default styles = StyleSheet.create({
  bodyContainer: {
    width: SIZES.width,
    height: SIZES.height * 0.9,
    flexDirection: 'column',
    alignItems: 'center',
  },
  instructionContainer: {
    width: SIZES.width,
    height: SIZES.height * 0.35,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  title: {
    fontSize: SIZES.padding2,
    fontWeight: 'bold',
    color: 'white',
  },
  headingText: {
    fontSize: SIZES.padding,
    fontWeight: 'bold',
    color: 'white',
  },
  subHeading: {
    color: 'white',
    fontSize: SIZES.h2,
    fontWeight: 'bold',
  },
  paragrapgh: {
    fontSize: SIZES.h3,
    color: 'white',
    fontWeight: 'bold',
  },

  questionCount: {
    width: SIZES.width * 0.2,
    height: SIZES.width * 0.1,
    borderRadius: 15,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: SIZES.width * 0.7,
    height: SIZES.height * 0.08,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: COLORS.primary,
    backgroundColor: COLORS.primarybg,
  },
  speakContainer: {
    width: SIZES.width,
    height: SIZES.height * 0.56,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  textInputStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
    width: '80%',
    height: 48,
    borderRadius: 20,
    paddingHorizontal: 16,
    shadowOffset: {width: 0, height: 1},
    shadowRadius: 2,
    elevation: 2,
    shadowOpacity: 0.4,
    marginTop: 10,
  },
  submitBtn: {
    marginTop: 24,
    backgroundColor: COLORS.primary,
    height: '10%',
    width: '30%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 25,
  },
  resultContainer: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-around',
    width: '100%',
    height: '70%',
  },
  listenImage: {
    width: SIZES.width * 0.28,
    height: SIZES.width * 0.28,
    borderRadius: (SIZES.width * 0.28) / 2,
    borderWidth: 1,
    borderColor: 'black',
    resizeMode: 'cover',
  },
  speechSettings: {
    width: SIZES.width * 0.18,
    height: SIZES.width * 0.18,
    borderRadius: (SIZES.width * 0.18) / 2,
    resizeMode: 'cover',
  },
});
